name: Spinoco webchat plugin github actions
on: [ push ]
jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            -   uses: docker://node:18.2.0-buster-slim
            -   uses: actions/checkout@v3
            -   uses: actions/cache@v3
                with:
                    path: node_modules
                    key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

            -   run: npm i --production=false

    lint:
        needs: [ install ]
        runs-on: ubuntu-latest
        steps:
            -   uses: docker://node:18.2.0-buster-slim
            -   uses: actions/checkout@v3
            -   uses: actions/cache@v3
                with:
                    path: node_modules
                    key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            -   run: npm run eslint

    build:
        needs: [ lint ]
        runs-on: ubuntu-latest
        steps:
            -   uses: docker://node:18.2.0-buster-slim
            -   uses: actions/checkout@v3
            -   uses: actions/cache@v3
                with:
                    path: node_modules
                    key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            -   run: npm run build
            -   uses: actions/upload-artifact@v3
                with:
                    name: pages
                    path: dist

    deploy:
        needs: [ build ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/download-artifact@v3
                with:
                    name: pages
                    path: .
            -   uses: actions/configure-pages@v1
            -   uses: actions/upload-pages-artifact@v1
                with:
                    path: .
            -   id: deployment
                uses: actions/deploy-pages@main
