name: Spinoco webchat plugin github actions
on: [push]
jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: docker://node:18.2.0-buster-slim
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

            - run: npm i --production=false

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: docker://node:18.2.0-buster-slim
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: node_modules
                  restore-keys: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            - run: npm run eslint

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: docker://node:18.2.0-buster-slim
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: node_modules
                  restore-keys: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            - run: npm run build
            - uses: actions/upload-artifact@v3
              with:
                name: webchat plugin dist artifact
                path: dist
